---
spring:
  profiles:
    active: 
    - 欢迎您！
---
spring:
  profiles: dev     #开发环境
  application:
    name: eureka-service-config-dev
---
spring:
  profiles: test      #测试环境
  application:
    name: eureka-service-config-test
